# compile and test person object
person:
	javac iperson.java person.java driver1.java

# compile hash table data structure including the persons it will store
table:
	javac iperson.java person.java itable.java table.java driver2.java

# remove the class files
clean:
	rm *.class
